/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateSubscriberArgs } from "./CreateSubscriberArgs";
import { UpdateSubscriberArgs } from "./UpdateSubscriberArgs";
import { DeleteSubscriberArgs } from "./DeleteSubscriberArgs";
import { SubscriberFindManyArgs } from "./SubscriberFindManyArgs";
import { SubscriberFindUniqueArgs } from "./SubscriberFindUniqueArgs";
import { Subscriber } from "./Subscriber";
import { SubscriberService } from "../subscriber.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Subscriber)
export class SubscriberResolverBase {
  constructor(
    protected readonly service: SubscriberService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Subscriber",
    action: "read",
    possession: "any",
  })
  async _subscribersMeta(
    @graphql.Args() args: SubscriberFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Subscriber])
  @nestAccessControl.UseRoles({
    resource: "Subscriber",
    action: "read",
    possession: "any",
  })
  async subscribers(
    @graphql.Args() args: SubscriberFindManyArgs
  ): Promise<Subscriber[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Subscriber, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Subscriber",
    action: "read",
    possession: "own",
  })
  async subscriber(
    @graphql.Args() args: SubscriberFindUniqueArgs
  ): Promise<Subscriber | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Subscriber)
  @nestAccessControl.UseRoles({
    resource: "Subscriber",
    action: "create",
    possession: "any",
  })
  async createSubscriber(
    @graphql.Args() args: CreateSubscriberArgs
  ): Promise<Subscriber> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Subscriber)
  @nestAccessControl.UseRoles({
    resource: "Subscriber",
    action: "update",
    possession: "any",
  })
  async updateSubscriber(
    @graphql.Args() args: UpdateSubscriberArgs
  ): Promise<Subscriber | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Subscriber)
  @nestAccessControl.UseRoles({
    resource: "Subscriber",
    action: "delete",
    possession: "any",
  })
  async deleteSubscriber(
    @graphql.Args() args: DeleteSubscriberArgs
  ): Promise<Subscriber | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
